name: test
on: push
jobs: 
    job:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v4
              - run: gcc 10.5.c -lm
              - run: sudo apt-get update
              - run: sudo apt-get install cmake
              - run: sudo apt-get install gnuplot-nox
              - run: sudo apt-get install texlive
              - run: gnuplot plot.gpi
              - run: mkdir build
              - run: cd build
              - run: cmake ..
              - run: ls
              - run: pdflatex art.tex
              - uses: actions/upload-artifact@v4
                with:
                  path: art.pdf
