name: test
on: push
jobs: 
    job:
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v4
              - run: gcc 10.5.c -lm
              - run: sudo apt-get install gnuplot-nox
              - run: gnuplot plot.gpi
              - run: ls
              - uses: actions/upload-artifact@v4
                with:
                  path: plot.pdf